name: Go test

on:
  push:
    branches:
      - "master"
      - "develop"
    tags:
      - 'v*'
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1.20 is the last version to support Windows < 10, Server < 2016, and MacOS < 1.15.
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'
          cache: true

      - name: Test
        run: go test -v ./...

#  integration_v2:
#    name: Deluge v2.0.3 integration test
#    needs: build
#    runs-on: ubuntu-18.04
#    steps:
#
#    - name: Download Linux build
#      uses: actions/download-artifact@v1
#      with:
#        name: linux-amd64
#        path: bin/
#
#    - name: Install Deluge v2.0.3
#      run: |
#        sudo bash bin/deluge-install.sh --v2
#
#    - name: Integration test
#      run: |
#        bash bin/deluge-integration.sh --v2

#  integration_v1:
#    name: Deluge v1.3 integration test
#    needs: build
#    runs-on: ubuntu-18.04
#    steps:
#
#    - name: Download Linux build
#      uses: actions/download-artifact@v1
#      with:
#        name: linux-amd64
#        path: bin/
#
#    - name: Install Deluge v1.3
#      run: |
#        sudo bash bin/deluge-install.sh --v1
#
#    - name: Integration test
#      run: |
#        bash bin/deluge-integration.sh --v1
